version: '3.8'
services:
  mysql:
    image: mysql:8.0  # Usamos la versión 8.0 de MySQL
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bankdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pruebatecnica
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3.9-management  # Usamos la versión 3.9 de RabbitMQ con UI de administración
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  mysql_data:
    driver: local
